BitBagCommerce/SyliusElasticsearchPlugin

- composer.json
- easy-coding-standard.neon
- easy-coding-standard.yml
- src/EntityRepository/ProductVariantRepositoryInterface.php
Updating coding standart version to the actual version from sylius
> Updating coding standart version

- src/Formatter/StringFormatter.php
For support Unicode non-latin characters
> Multibyte strtolower

- src/Resources/config/services/controller.yml
> Make controller service compatible with Symfony 4

- src/PropertyBuilder/AttributeTaxonsBuilder.php
It will be faster when searching only current attribute values
> Optimize AttributeTaxonsBuilder

- spec/Transformer/Product/ChannelPricingTransformerSpec.php
- spec/Transformer/Product/ImageTransformerSpec.php
- spec/Transformer/Product/SlugTransformerSpec.php
- src/Controller/Action/Api/ListProductsByPartialNameAction.php
- src/QueryBuilder/ContainsNameQueryBuilder.php
- src/Resources/config/services/controller/api.xml
- src/Resources/config/services/transformer.xml
- src/Resources/public/css/bitbag-autocomplete-search.css
- src/Resources/views/Shop/Product/index.html.twig
- src/Transformer/Product/ChannelPricingTransformer.php
- src/Transformer/Product/ImageTransformer.php
- src/Transformer/Product/SlugTransformer.php
- src/Transformer/Product/TransformerInterface.php
> More accurate searches and separated responsibilities of Action

- src/QueryBuilder/HasPriceBetweenQueryBuilder.php
- src/Resources/translations/messages.fr.yml
See #56 
Adding french translations btw
> Solving non numerical value error and adding french translations

- spec/Transformer/Product/ChannelPricingTransformerSpec.php
- src/Controller/Response/DTO/Item.php
- src/Transformer/Product/ChannelPricingTransformer.php
This error occurred when the product has no any variant
> Fix error `Call to a member function getChannelPricingForChannel()

- README.md
Added a note about supported ElasticSearch versions to help save someone else some time :)
> Updated README.md with ElasticSearch Versions

- src/QueryBuilder/HasPriceBetweenQueryBuilder.php
Notice level error thrown if min or max price is not set, isset condition added to prevent it
> Notice level error for missing min or max price

- src/QueryBuilder/HasPriceBetweenQueryBuilder.php
Reverts BitBagCommerce/SyliusElasticsearchPlugin#103
> Revert "Notice level error for missing min or max price"

- src/PropertyBuilder/OptionTaxonsBuilder.php
- src/Resources/config/services/property_builder.xml
https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/issues/131
> Remove unused variable

- spec/PropertyBuilder/OptionTaxonsBuilderSpec.php
- spec/QueryBuilder/HasPriceBetweenQueryBuilderSpec.php
- src/QueryBuilder/HasPriceBetweenQueryBuilder.php
- tests/Behat/Service/Populate.php
Changed number parsing in price range queries, to fix rounding issues.
> Changed rounding/number parsing in price range quries

- spec/PropertyBuilder/OptionTaxonsBuilderSpec.php
- tests/Behat/Service/Populate.php
https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/commit/bc965ae5593fcfb0d0700601f91e30ed83683f2b#diff-023f032d1c4a4eb559764b803528a6c789ad9c1cef168fb351115ee49b9f860fL47
> Removed one the parameters to fix failing spec

- composer.json
- spec/Controller/Action/Shop/ListProductsActionSpec.php
- src/Controller/Action/Shop/ListProductsAction.php
- src/Form/Type/PriceFilterType.php
- src/QueryBuilder/HasPriceBetweenQueryBuilder.php
- src/Resources/translations/validators.en.yml
| Q               | A
| --------------- | -----
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | 
| License         | MIT
Adds validation to price fields in product filter page.
> Validating prices in search filter

- README.md
- spec/Controller/RequestDataHandler/PaginationDataHandlerSpec.php
- src/Controller/RequestDataHandler/PaginationDataHandler.php
- src/Controller/RequestDataHandler/PaginationDataHandlerInterface.php
- src/Resources/config/config.yml
- src/Resources/config/services/controller.xml
- src/Resources/views/Shop/Product/Index/_pagination.html.twig
> Added possibility to set own pagination limits

- README.md
- UPGRADE-1.7.md
- src/EventListener/ResourceIndexListener.php
- src/EventListener/ResourceIndexListenerInterface.php
- src/Model/ProductVariantInterface.php
- src/Model/ProductVariantTrait.php
- src/Resources/config/services/event_listener.xml
+ added possible to populate parent on another resource action (add new / edit)
> refresh product on  variant save

- README.md
> _horizontalMenu.html.twig file name fixed in Usage section

- .github/workflows/build.yml
Include pipeline tests for PHP 8 on Sylius ~1.10
> Removed exclude

- composer.json
Conflict with "doctrine/orm": ">=2.15.2" removed. Bug should be fixed with orm 2.15.3
> Removed conflict from composer.json

- src/Controller/Action/Shop/ListProductsAction.php
Fix of error : 
```
request.CRITICAL: Uncaught PHP Exception Symfony\Component\Form\Exception\LogicException: "Cannot check if an unsubmitted form is valid. Call Form::isSubmitted() before Form::isValid()." at /home/site/vendor/symfony/form/Form.php line 765 {"exception":"[object] (Symfony\\Component\\Form\\Exception\\LogicException(code: 0): Cannot check if an unsubmitted form is valid. Call Form::isSubmitted() before Form::isValid(). at /home/site/vendor/symfony/form/Form.php:765)"} []
```
> Fix form error
